package com.zhiwang.zfm.entity.sys.query;

import com.zhiwang.zfm.common.page.BaseSearchForm;

public class SysAreaSearchForm extends BaseSearchForm {
	
		private String id;			//	private String parentId;			//	private String name;			//	private String shortName;			//	private String megerShortName;			//	private Integer levelType;			//	private String cityCode;			//	private String zipCode;			//	private String pinyin;			//	private String jianpin;			//	private String firstChar;			//	private String remark;			//	public String getId() {	    return this.id;	}	public void setId(String id) {	    this.id=id;	}	public String getParentId() {	    return this.parentId;	}	public void setParentId(String parentId) {	    this.parentId=parentId;	}	public String getName() {	    return this.name;	}	public void setName(String name) {	    this.name=name;	}	public String getShortName() {	    return this.shortName;	}	public void setShortName(String shortName) {	    this.shortName=shortName;	}	public String getMegerShortName() {	    return this.megerShortName;	}	public void setMegerShortName(String megerShortName) {	    this.megerShortName=megerShortName;	}	public Integer getLevelType() {	    return this.levelType;	}	public void setLevelType(Integer levelType) {	    this.levelType=levelType;	}	public String getCityCode() {	    return this.cityCode;	}	public void setCityCode(String cityCode) {	    this.cityCode=cityCode;	}	public String getZipCode() {	    return this.zipCode;	}	public void setZipCode(String zipCode) {	    this.zipCode=zipCode;	}	public String getPinyin() {	    return this.pinyin;	}	public void setPinyin(String pinyin) {	    this.pinyin=pinyin;	}	public String getJianpin() {	    return this.jianpin;	}	public void setJianpin(String jianpin) {	    this.jianpin=jianpin;	}	public String getFirstChar() {	    return this.firstChar;	}	public void setFirstChar(String firstChar) {	    this.firstChar=firstChar;	}	public String getRemark() {	    return this.remark;	}	public void setRemark(String remark) {	    this.remark=remark;	}
	
}
