package com.nyd.capital.service.utils;

import java.util.HashMap;
import java.util.Map;

/**
 * Cong Yuxiang
 * 2017/11/21
 **/
public class Constants {
    public static final String WSM="wsm";

    public static final String KZJR_LOCK_PREFIX = "kzjrlock";
    public static final String KZJR_PREFIX = "kzjr";

    public static final String KZJR_CALLBACK_PREFIX="kzjrcb";
    public static final String WT_CALLBACK_PREFIX = "wtcb";
    public static final String QCGZ_CALLBACK_PREFIX = "qcgzcb";
    public static final String DLD_CALLBACK_PREFIX = "dldcb";
    public static final String KDLC_CALLBACK_PREFIX = "kdlccb";
    public static final String KDLC_CALLBACK_PREFIX_NOTICE = "kdlcnoitce";
    public static final String DLD_USER_BALANCE_PREFIX = "dldbalance";
    public static final String JX_CALLBACK_PREFIX = "jxgzcb";
    public static final String JX_CALLBACK_PASH = "jxgzcbpash";
    public static final String JX_CALLBACK_HTML = "jxgzcbhtml";
    public static final String JX_CALLBACK_WITHDRAW = "jxgzcbwithdraw";
    public static final String JX_CALLBACK_WITHDRAW_SIGN = "jxgzcbwithdrawsign";

    public static final String KZJR_SPLIT="S";
    public static final String NYD_DD_TALK = "nydddtalk";
    public static final String CAPITAL_QUERY_KEY = "capitalquerykey";
    public static final String POCKET_CALLBACK_PREFIX = "pocketcb";
    public static final String CAPITAL_KEY = "capitalkey";
    public static final String RESEND_CAPITAL_KEY = "resend:capital:";
    public static final String WITHHOLD_TASK = "withholdTask";


    public static Map<String,String> map = new HashMap<>();
    public static Map<String,String> relationMap = new HashMap<>();
    public static Map<String,String> maritalMap = new HashMap<>();
    public static Map<String,String> eduMap = new HashMap<>();
    static {
        relationMap.put("父母","1");
        relationMap.put("配偶","2");
        relationMap.put("亲戚","3");
        relationMap.put("朋友","4");
        relationMap.put("同事","5");
        relationMap.put("兄妹","3");
        relationMap.put("其他","4");

        maritalMap.put("已婚","2");
        maritalMap.put("未婚","1");
        maritalMap.put("离婚","4");
        maritalMap.put("丧偶","3");

        eduMap.put("硕士及以上","2");
        eduMap.put("本科","3");
        eduMap.put("大专","4");
        eduMap.put("中专","5");
        eduMap.put("技校","6");
        eduMap.put("高中","7");
        eduMap.put("初中","8");
        eduMap.put("小学","9");
        eduMap.put("其他","10");

        map.put("中国银行","1001");
        map.put("中国农业银行","1002");
        map.put("中国工商银行","1003");
        map.put("中国建设银行","1004");
        map.put("中国交通银行","1005");
        map.put("中国邮政储蓄银行","1006");
        map.put("中信银行","2001");
        map.put("中国光大银行","2002");
        map.put("华夏银行","2003");
        map.put("中国民生银行","2004");
        map.put("招商银行","2005");
        map.put("兴业银行","2006");
        map.put("广发银行","2007");
        map.put("平安银行","2008");
        map.put("上海浦东发展银行","2009");
        map.put("恒丰银行","2010");
        map.put("浙商银行","2011");
        map.put("渤海银行","2012");
        map.put("城市商业银行","3001");
        map.put("北京银行","3002");
        map.put("天津银行","3003");
        map.put("河北银行","3004");
        map.put("唐山市商业银行","3005");
        map.put("承德银行","3006");
        map.put("张家口市商业银行","3007");
        map.put("秦皇岛银行","3008");
        map.put("邢台银行","3009");
        map.put("廊坊银行","3010");
        map.put("保定银行","3011");
        map.put("邯郸银行","3012");
        map.put("衡水银行","3013");
        map.put("晋商银行","3014");
        map.put("大同市商业银行","3015");
        map.put("长治银行","3016");
        map.put("晋城银行","3017");
        map.put("晋中银行","3018");
        map.put("阳泉市商业银行","3019");
        map.put("包商银行","3020");
        map.put("内蒙古银行","3021");
        map.put("乌海银行","3022");
        map.put("鄂尔多斯银行","3023");
        map.put("盛京银行","3024");
        map.put("鞍山银行","3025");
        map.put("抚顺银行","3026");
        map.put("本溪市商业银行","3027");
        map.put("丹东银行","3028");
        map.put("锦州银行","3029");
        map.put("锦州银行","3030");
        map.put("营口银行","3031");
        map.put("阜新银行","3032");
        map.put("辽阳银行","3033");
        map.put("铁岭银行","3034");
        map.put("朝阳银行","3035");
        map.put("盘锦市商业银行","3036");
        map.put("葫芦岛银行","3037");
        map.put("营口沿海银行","3038");
        map.put("吉林银行","3039");
        map.put("龙江银行","3040");
        map.put("哈尔滨银行","3041");
        map.put("上海银行","3042");
        map.put("江苏银行","3043");
        map.put("南京银行","3044");
        map.put("江苏长江商业银行","3045");
        map.put("苏州银行","3046");
        map.put("杭州银行","3047");
        map.put("温州银行","3048");
        map.put("嘉兴银行","3049");
        map.put("湖州银行","3050");
        map.put("绍兴银行","3051");
        map.put("金华银行","3052");
        map.put("浙江稠州商业银行","3053");
        map.put("台州商行","3054");
        map.put("浙江泰隆商业银行","3055");
        map.put("浙江民泰商业银行","3056");
        map.put("宁波银行","3057");
        map.put("徽商银行","3058");
        map.put("福建海峡银行","3059");
        map.put("泉州银行","3060");
        map.put("南昌银行","3061");
        map.put("九江银行","3062");
        map.put("赣州银行","3063");
        map.put("上饶银行","3064");
        map.put("景德镇市商业银行","3065");
        map.put("齐鲁银行","3066");
        map.put("齐商银行","3067");
        map.put("烟台银行","3068");
        map.put("潍坊银行","3069");
        map.put("临商银行","3070");
        map.put("威海市商业银行","3071");
        map.put("日照银行","3072");
        map.put("德州银行","3073");
        map.put("莱商银行","3074");
        map.put("东营银行","3075");
        map.put("济宁银行","3076");
        map.put("泰安市商业银行","3077");
        map.put("枣庄银行","3078");
        map.put("郑州银行","3079");
        map.put("开封市商业银行","3080");
        map.put("洛阳银行","3081");
        map.put("南阳银行","3082");
        map.put("新乡银行","3083");
        map.put("焦作市商业银行","3084");
        map.put("许昌银行","3085");
        map.put("平顶山银行","3086");
        map.put("鹤壁银行","3087");
        map.put("信阳银行","3088");
        map.put("安阳银行","3089");
        map.put("驻马店银行","3090");
        map.put("三门峡市银行","3091");
        map.put("漯河银行","3092");
        map.put("周口银行","3093");
        map.put("商丘银行","3094");
        map.put("濮阳银行","3095");
        map.put("湖北银行","3096");
        map.put("汉口银行","3097");
        map.put("长沙银行","3098");
        map.put("华融湘江银行","3099");
        map.put("广州银行","3100");
        map.put("珠海华润银行","3101");
        map.put("广东南粤银行","3102");
        map.put("东莞银行","3103");
        map.put("广东华兴银行","3104");
        map.put("广西北部湾银行","3105");
        map.put("柳州银行","3106");
        map.put("桂林银行","3107");
        map.put("重庆银行","3108");
        map.put("重庆三峡银行","3109");
        map.put("成都银行","3110");
        map.put("泸州市商业银行","3111");
        map.put("攀枝花市商业银行","3112");
        map.put("宜宾市商业银行","3113");
        map.put("乐山市商业银行","3114");
        map.put("南充市商业银行","3115");
        map.put("自贡市商业银行","3116");
        map.put("德阳银行","3117");
        map.put("遂宁市商业银行","3118");
        map.put("绵阳市商业银行","3119");
        map.put("凉山州商业银行","3120");
        map.put("雅安市商业银行","3121");
        map.put("达州市商业银行","3122");
        map.put("贵阳银行","3123");
        map.put("贵州银行","3124");
        map.put("富滇银行","3125");
        map.put("曲靖市商业银行","3126");
        map.put("玉溪市商业银行","3127");
        map.put("西藏银行","3128");
        map.put("长安银行","3129");
        map.put("西安银行","3130");
        map.put("兰州银行","3131");
        map.put("甘肃银行","3132");
        map.put("青海银行","3133");
        map.put("宁夏银行","3134");
        map.put("石嘴山银行","3135");
        map.put("乌鲁木齐市商业银行","3136");
        map.put("昆仑银行","3137");
        map.put("新疆汇和银行","3138");
        map.put("库尔勒市商业银行","3139");
        map.put("哈密市商业银行","3140");
        map.put("大连银行","3141");
        map.put("宁波东海银行","3142");
        map.put("宁波通商银行","3143");
        map.put("厦门银行","3144");
        map.put("厦门国际银行","3145");
        map.put("青岛银行","3146");
        map.put("北京农村商业银行股份有限公司","4001");
        map.put("天津农村商业银行","4002");
        map.put("天津滨海农村商业银行","4003");
        map.put("沧州融信农村商业银行股份有限公司","4004");
        map.put("鄂尔多斯农村商业银行","4005");
        map.put("沈阳农村商业银行","4006");
        map.put("吉林九台农村商业银行股份有限公司","4007");
        map.put("长春农村商业银行股份有限公司","4008");
        map.put("上海农商行","4009");
        map.put("江苏高淳农村商业银行","4010");
        map.put("江苏溧水农村商业银行","4011");
        map.put("徐州淮海农村商业银行","4012");
        map.put("江苏新沂农村商业银行","4013");
        map.put("江苏邳州农村商业银行","4014");
        map.put("江苏宜兴农村商业银行","4015");
        map.put("江苏扬中农村商业银行","4016");
        map.put("江苏丹阳农村商业银行","4017");
        map.put("江苏句容农村商业银行","4018");
        map.put("江苏镇江农村商业银行","4019");
        map.put("江苏宝应农村商业银行","4020");
        map.put("江苏仪征农村商业银行","4021");
        map.put("江苏高邮农村商业银行","4022");
        map.put("江苏江都农村商业银行","4023");
        map.put("江苏金湖农村商业银行","4024");
        map.put("江苏盱眙农村商业银行","4025");
        map.put("江苏涟水农村商业银行","4026");
        map.put("江苏淮安农村商业银行","4027");
        map.put("连云港东方农村商业银行","4028");
        map.put("江苏赣榆农村商业银行","4029");
        map.put("江苏沭阳农村商业银行","4030");
        map.put("江苏泗洪农村商业银行","4031");
        map.put("江苏泗阳农村商业银行","4032");
        map.put("江苏民丰农村商业银行","4033");
        map.put("江苏兴化农村商业银行","4034");
        map.put("江苏泰州农村商业银行","4035");
        map.put("江苏姜堰农村商业银行","4036");
        map.put("江苏东台农村商业银行","4037");
        map.put("江苏响水农村商业银行","4038");
        map.put("江苏大丰农村商业银行","4039");
        map.put("江苏阜宁农村商业银行","4040");
        map.put("江苏建湖农村商业银行","4041");
        map.put("江苏盐城黄海农村商业银行","4042");
        map.put("江苏如东农村商业银行","4043");
        map.put("江苏启东农村商业银行","4044");
        map.put("江苏海安农村商业银行","4045");
        map.put("江苏海门农村商业银行","4046");
        map.put("江苏如皋农村商业银行","4047");
        map.put("江苏南通农村商业银行","4048");
        map.put("江苏紫金农村商业银行","4049");
        map.put("无锡农村商业银行","4050");
        map.put("江阴农村商业银行","4051");
        map.put("常熟农村商业银行","4052");
        map.put("张家港农村商业银行","4053");
        map.put("吴江农村商业银行","4054");
        map.put("昆山农村商业银行","4055");
        map.put("太仓农村商业银行","4056");
        map.put("江苏射阳农村商业银行","4057");
        map.put("靖江农村商业银行","4058");
        map.put("江南农村商业银行","4059");
        map.put("丰县农村商业银行","4060");
        map.put("杭州联合农村商业银行","4061");
        map.put("浙江萧山农村商业银行股份有限公司","4062");
        map.put("浙江杭州余杭农村商业银行股份有限公司","4063");
        map.put("浙江富阳农村商业银行股份有限公司","4064");
        map.put("浙江温州鹿城农村商业银行股份有限公司","4065");
        map.put("浙江瓯海农村商业银行股份有限公司","4066");
        map.put("浙江温州龙湾农村商业银行股份有限公司","4067");
        map.put("浙江瑞安农村商业银行股份有限公司","4068");
        map.put("浙江乐清农村商业银行股份有限公司","4069");
        map.put("浙江永嘉农村商业银行股份有限公司","4070");
        map.put("浙江苍南农村商业银行股份有限公司","4071");
        map.put("浙江禾城农村商业银行股份有限公司","4072");
        map.put("浙江嘉善农村商业银行股份有限公司","4073");
        map.put("浙江海宁农村商业银行股份有限公司","4074");
        map.put("浙江安吉农村商业银行股份有限公司","4075");
        map.put("浙江德清农村商业银行股份有限公司","4076");
        map.put("浙江绍兴瑞丰农村商业银行股份有限公司","4077");
        map.put("浙江诸暨农村商业银行股份有限公司","4078");
        map.put("浙江上虞农村商业银行股份有限公司","4079");
        map.put("浙江新昌农村商业银行股份有限公司","4080");
        map.put("浙江金华成泰农村商业银行股份有限公司","4081");
        map.put("浙江义乌农村商业银行股份有限公司","4082");
        map.put("浙江永康农村商业银行股份有限公司","4083");
        map.put("浙江东阳农村商业银行股份有限公司","4084");
        map.put("浙江江山农村商业银行股份有限公司","4085");
        map.put("浙江天台农村商业银行股份有限公司","4086");
        map.put("浙江丽水莲都农村商业银行股份有限公司","4087");
        map.put("浙江青田农村商业银行股份有限公司","4088");
        map.put("浙江舟山定海海洋农村商业银行股份有限公司","4089");
        map.put("浙江舟山普陀农村商业银行股份有限公司","4090");
        map.put("浙江南浔农村商业银行股份有限公司","4091");
        map.put("景德镇农商银行","4092");
        map.put("新余农商银行","4093");
        map.put("九江农商银行","4094");
        map.put("宜春农商银行","4095");
        map.put("吉安农村商业银行","4096");
        map.put("赣州农村商业银行","4097");
        map.put("南昌农村商业银行股份有限公司","4098");
        map.put("武汉农村商业银行","4099");
        map.put("广州农村商业银行股份有限公司","4100");
        map.put("佛山顺德农村商业银行股份有限公司","4101");
        map.put("东莞农村商业银行股份有限公司","4102");
        map.put("广东河源农村商业银行股份有限公司","4103");
        map.put("肇庆端州农村商业银行股份有限公司","4104");
        map.put("广东阳东农村商业银行股份有限公司","4105");
        map.put("广东揭阳农村商业银行股份有限公司","4106");
        map.put("广东揭西农村商业银行股份有限公司","4107");
        map.put("广西资源农村商业银行股份有限公司","4108");
        map.put("广西田东农村商业银行股份有限公司","4109");
        map.put("广西融安农村商业银行股份有限公司","4110");
        map.put("广西蒙山农村商业银行股份有限公司","4111");
        map.put("广西田阳农村商业银行股份有限公司","4112");
        map.put("广西恭城农村商业银行股份有限公司","4113");
        map.put("广西龙胜农村商业银行股份有限公司","4114");
        map.put("广西灌阳农村商业银行股份有限公司","4115");
        map.put("广西昭平农村商业银行股份有限公司","4116");
        map.put("广西凌云农村商业银行股份有限公司","4117");
        map.put("重庆农村商业银行股份有限公司","4118");
        map.put("成都农商银行","4119");
        map.put("贵阳农村商业银行","4120");
        map.put("灵武农村商业银行","4121");
        map.put("宁夏平罗农村商业银行","4122");
        map.put("宁夏吴忠农村商业银行","4123");
        map.put("宁夏中卫农村商业银行","4124");
        map.put("宁夏黄河农村商业银行股份有限公司","4125");
        map.put("厦门农村商业银行股份有限公司","4126");
        map.put("青岛农商银行","4127");
        map.put("深圳农村商业银行","4128");
        map.put("江苏省农村信用社联合社","4129");
        map.put("安徽省农村信用社联合社","4130");
        map.put("河南省农村信用社联合社","4131");
        map.put("江西省农村信用社联合社","4132");
        map.put("湖北省农村信用社联合社","4133");
        map.put("河北省农村信用社联合社","4134");
        map.put("山东省农村信用社联合社","4135");
        map.put("黑龙江省农村信用社联合社 ","4136");
        map.put("辽宁省农村信用社联合社 ","4137");
        map.put("吉林省农村信用社联合社 ","4138");
        map.put("湖南省农村信用社联合社 ","4139");
        map.put("山西省农村信用社联合社","4140");
        map.put("陕西省农村信用社联合社","4141");
        map.put("浙江省农村信用社联合社","4142");
        map.put("福建省农村信用社联合社","4143");
        map.put("广东省农村信用社联合社","4144");
        map.put("海南省农村信用社联合社","4145");
        map.put("四川省农村信用社联合社","4146");
        map.put("云南省农村信用社联合社","4147");
        map.put("贵州省农村信用社联合社","4148");
        map.put("青海省农村信用社联合社","4149");
        map.put("甘肃省农村信用社联合社","4150");
        map.put("内蒙古自治区农村信用社联合社","4151");
        map.put("宁夏农村信用社联合社","4152");
        map.put("新疆维吾尔自治区农村信用社联合社","4153");
        map.put("西藏自治区农村信用社联合社","4154");
        map.put("广西农村信用社","4155");
        map.put("上海农村信用社","4156");
    }
    public static String getBh(String bankName){
        return map.get(bankName);
    }
}
